import type { Metadata } from 'next'

import { Box } from '@mui/material'
export const metadata: Metadata = {
  title: 'Datacakra App',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '100vh',
        width: '100%',
      }}
      id="auth-layout"
    >
      {children}
    </Box>
  )
}
