import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Datacakra App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script type='text/javascript' src='//pl25989910.effectiveratecpm.com/7f/ee/98/7fee98e98863a33fa0b98dd61cc80211.js'></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
