import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Script from "next/script";
export const metadata: Metadata = {
  title: 'Datacakra App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <html lang="en">
      <head>
        <meta name="monetag" content="c9ff73f802af07c9570a3a296952a223"/>
        <Script
          src="//pl25989910.effectiveratecpm.com/7f/ee/98/7fee98e98863a33fa0b98dd61cc80211.js"
          strategy="beforeInteractive"
        />

      </head>
      <body>
        
        <Script id="popunder-script" strategy="afterInteractive">
          {`
            window.atOptions = {
              key: '0b827f359b2c70c0a1d75d8c73e1e72c',
              format: 'iframe',
              height: 250,
              width: 300,
              params: {}
            };
          `}
        </Script>
        <Script
          src="//www.highperformanceformat.com/0b827f359b2c70c0a1d75d8c73e1e72c/invoke.js"
          strategy="afterInteractive"
        />
        <Script
          src="//pl25990105.effectiveratecpm.com/b50ded3f87426b00d0901ee8d86494be/invoke.js"
          strategy="afterInteractive"
          async
          data-cfasync="false"
        />
               <div id="container-b50ded3f87426b00d0901ee8d86494be"></div>

        {children}
      </body>
    </html>
  )
}
