import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navbar from '@/components/Navbar'
import { Box } from '@mui/material'

export const metadata: Metadata = {
  title: 'Datacakra App',
  description: 'Generated by create next app',
}

export default function ProtectedLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
      }}
      id="protected-layout"
    >
      <Navbar />
      <main>{children}</main>
    </Box>
  )
}
